name: Release Plugin

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Get Plugin Name
        id: plugin-name
        run: |
          PLUGIN_NAME=$(grep -Po 'namespace\s+\K[^;]+' ./CommentToTelegram/Plugin.php | awk -F '\\' '{print $NF}')
          echo "plugin_name=$PLUGIN_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract Version Number
        id: extract-version
        run: |
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed -E 's/^v?((([0-9]+\.)*[0-9]+))$/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Zip Plugin
        id: zip-plugin
        run: |
          sed -i "s/%version%/${{ steps.extract-version.outputs.version }}/g" ./CommentToTelegram/Plugin.php
          PLUGIN_ZIP="${{ steps.plugin-name.outputs.plugin_name }}-${{ steps.extract-version.outputs.version }}.zip"
          zip -r "$PLUGIN_ZIP" . --exclude ".github/*"
          echo "plugin_zip=$PLUGIN_ZIP" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload Plugin To Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.zip-plugin.outputs.plugin_zip }}
          asset_name: ${{ steps.zip-plugin.outputs.plugin_zip }}
          asset_content_type: application/zip
